#pragma once
#include <cstdlib>

char syscalls_a0[][100] = {
	"FileOpen(filename, accessmode)",
	"FileSeek(fd, offset, seektype)",
	"FileRead(fd, dst, length)",
	"FileWrite(fd, src, length)",
	"FileClose(fd)",
	"FileIoctl(fd, cmd, arg)",
	"exit(exitcode)",
	"FileGetDeviceFlag(fd)",
	"FileGetc(fd)",
	"FilePutc(char, fd)",
	"todigit(char)",
	"atof(src); Does NOT work - uses(ABSENT) cop1 !!!",
	"strtoul(src, src_end, base)",
	"strtol(src, src_end, base)",
	"abs(val)",
	"labs(val)",
	"atoi(src)",
	"atol(src)",
	"atob(src, num_dst)",
	"SaveState(buf)",
	"RestoreState(buf, param)",
	"strcat(dst, src)",
	"strncat(dst, src, maxlen)",
	"strcmp(str1, str2)",
	"strncmp(str1, str2, maxlen)",
	"strcpy(dst, src)",
	"strncpy(dst, src, maxlen)",
	"strlen(src)",
	"index(src, char)",
	"rindex(src, char)",
	"strchr(src, char);",
	"strrchr(src, char);",
	"strpbrk(src, list)",
	"strspn(src, list)",
	"strcspn(src, list)",
	"strtok(src, list);",
	"strstr(str, substr)",
	"toupper(char)",
	"tolower(char)",
	"bcopy(src, dst, len)",
	"bzero(dst, len)",
	"bcmp(ptr1, ptr2, len);",
	"memcpy(dst, src, len)",
	"memset(dst, fillbyte, len)",
	"memmove(dst, src, len);",
	"memcmp(src1, src2, len);",
	"memchr(src, scanbyte, len)",
	"rand()",
	"srand(seed)",
	"qsort(base, nel, width, callback)",
	"strtod(src, src_end); Does NOT work - uses(ABSENT) cop1 !!!",
	"malloc(size)",
	"free(buf)",
	"lsearch(key, base, nel, width, callback)",
	"bsearch(key, base, nel, width, callback)",
	"calloc(sizx, sizy);",
	"realloc(old_buf, new_siz);",
	"InitHeap(addr, size)",
	"SystemErrorExit(exitcode)",
	"std_in_getchar()",
	"std_out_putchar(char)",
	"std_in_gets(dst)",
	"std_out_puts(src)",
	"printf(txt, param1, param2, etc.)",
	"SystemErrorUnresolvedException()",
	"LoadExeHeader(filename, headerbuf)",
	"LoadExeFile(filename, headerbuf)",
	"DoExecute(headerbuf, param1, param2)",
	"FlushCache()",
	"init_a0_b0_c0_vectors",
	"GPU_dw(Xdst, Ydst, Xsiz, Ysiz, src)",
	"gpu_send_dma(Xdst, Ydst, Xsiz, Ysiz, src)",
	"SendGP1Command(gp1cmd)",
	"GPU_cw(gp0cmd); send GP0 command word",
	"GPU_cwp(src, num); send GP0 command word and parameter words",
	"send_gpu_linked_list(src)",
	"gpu_abort_dma()",
	"GetGPUStatus()",
	"gpu_sync()",
	"SystemError",
	"SystemError",
	"oadAndExecute(filename, stackbase, stackoffset)",
	"SystemError",
	"SystemError;",
	"CdInit()",
	"_bu_init()",
	"CdRemove();",
	"return 0",
	"return 0",
	"return 0",
	"return 0",
	"dev_tty_init(); PS2: SystemError",
	"dev_tty_open(fcb, and unused : path\name, accessmode)",
	"dev_tty_in_out(fcb, cmd)",
	"dev_tty_ioctl(fcb, cmd, arg)",
	"dev_cd_open(fcb, path\name, accessmode)",
	"dev_cd_read(fcb, dst, len)",
	"dev_cd_close(fcb)",
	"dev_cd_firstfile(fcb, path\name, direntry)",
	"dev_cd_nextfile(fcb, direntry)",
	"dev_cd_chdir(fcb, path)",
	"dev_card_open(fcb, path\name, accessmode)",
	"dev_card_read(fcb, dst, len)",
	"dev_card_write(fcb, src, len)",
	"dev_card_close(fcb)",
	"dev_card_firstfile(fcb,path\name, direntry)",
	"dev_card_nextfile(fcb, direntry)",
	"dev_card_erase(fcb, path\name)",
	"dev_card_undelete(fcb, path\name)",
	"dev_card_format(fcb)",
	"dev_card_rename(fcb1, path\name, fcb2, path\name)",
	"card_clear_error(fcb)",
	"_bu_init()",
	"CdInit()",
	"CdRemove()",
	"return 0",
	"return 0",
	"return 0",
	"return 0",
	"return 0",
	"CdAsyncSeekL(src)",
	"return 0",
	"return 0",
	"return 0",
	"CdAsyncGetStatus(dst)",
	"return 0",
	"CdAsyncReadSector(count, dst, mode)",
	"return 0",
	"return 0",
	"CdAsyncSetMode(mode)",
	"return 0",
	"return 0",
	"return 0",
	"return 0 or reportedly, CdStop(? )",
	"return 0",
	"return 0",
	"return 0",
	"return 0",
	"return 0",
	"return 0",
	"return 0 ",
	"return 0",
	"return 0",
	"return 0",
	"CdromIoIrqFunc1()",
	"CdromDmaIrqFunc1()",
	"CdromIoIrqFunc2()",
	"CdromDmaIrqFunc2()",
	"CdromGetInt5errCode(dst1, dst2)",
	"CdInitSubFunc()",
	"AddCDROMDevice()",
	"AddMemCardDevice()",
	"AddDuartTtyDevice()",
	"AddDummyTtyDevice()",
	"SystemError",
	"SystemError",
	"SetConf(num_EvCB, num_TCB, stacktop)",
	"GetConf(num_EvCB_dst, num_TCB_dst, stacktop_dst)",
	"SetCdromIrqAutoAbort(type, flag)",
	"SetMemSize(megabytes)",
	"WarmBoot()",
	"SystemErrorBootOrDiskFailure(type,errorcode)",
	"EnqueueCdIntr()",
	"DequeueCdIntr()",
	"CdGetLbn(filename)",
	"CdReadSector(count,sector,buffer)",
	"CdGetStatus()",
	"bu_callback_okay()",
	"bu_callback_err_write()",
	"bu_callback_err_busy()",
	"bu_callback_err_eject()",
	"_card_info(port)",
	"_card_async_load_directory(port)",
	"set_card_auto_format(flag)",
	"bu_callback_err_prev_write()",
	"card_write_test(port)",
	"return 0",
	"return 0",
	"ioabort_raw(param)",
	"return 0",
	"GetSystemInfo(index)"
};

char syscalls_b0[][100] = {
	/* 0x00 */	"SysMalloc",
	/* 0x01 */	"bios_b0_01",
	/* 0x02 */	"bios_b0_02",
	/* 0x03 */	"bios_b0_03",
	/* 0x04 */	"bios_b0_04",
	/* 0x05 */	"bios_b0_05",
	/* 0x06 */	"bios_b0_06",
	/* 0x07 */	"DeliverEvent",
	/* 0x08 */	"OpenEvent",
	/* 0x09 */	"CloseEvent",
	/* 0x0a */	"WaitEvent",
	/* 0x0b */	"TestEvent",
	/* 0x0c */	"EnableEvent",
	/* 0x0d */	"DisableEvent",
	/* 0x0e */	"OpenTh",
	/* 0x0f */	"CloseTh",
	/* 0x10 */	"ChangeTh",
	/* 0x11 */	"bios_b0_11",
	/* 0x12 */	"InitPAD",
	/* 0x13 */	"StartPAD",
	/* 0x14 */	"StopPAD",
	/* 0x15 */	"PAD_init",
	/* 0x16 */	"PAD_dr",
	/* 0x17 */	"ReturnFromException",
	/* 0x18 */	"ResetEntryInt",
	/* 0x19 */	"HookEntryInt",
	/* 0x1a */	"bios_b0_1a",
	/* 0x1b */	"bios_b0_1b",
	/* 0x1c */	"bios_b0_1c",
	/* 0x1d */	"bios_b0_1d",
	/* 0x1e */	"bios_b0_1e",
	/* 0x1f */	"bios_b0_1f",
	/* 0x20 */	"UnDeliverEvent",
	/* 0x21 */	"bios_b0_21",
	/* 0x22 */	"bios_b0_22",
	/* 0x23 */	"bios_b0_23",
	/* 0x24 */	"bios_b0_24",
	/* 0x25 */	"bios_b0_25",
	/* 0x26 */	"bios_b0_26",
	/* 0x27 */	"bios_b0_27",
	/* 0x28 */	"bios_b0_28",
	/* 0x29 */	"bios_b0_29",
	/* 0x2a */	"bios_b0_2a",
	/* 0x2b */	"bios_b0_2b",
	/* 0x2c */	"bios_b0_2c",
	/* 0x2d */	"bios_b0_2d",
	/* 0x2e */	"bios_b0_2e",
	/* 0x2f */	"bios_b0_2f",
	/* 0x30 */	"bios_b0_30",
	/* 0x31 */	"bios_b0_31",
	/* 0x32 */	"open(b0)",
	/* 0x33 */	"lseek(b0)",
	/* 0x34 */	"read(b0)",
	/* 0x35 */	"write(b0)",
	/* 0x36 */	"close(b0)",
	/* 0x37 */	"ioctl(b0)",
	/* 0x38 */	"exit(b0)",
	/* 0x39 */	"bios_b0_39",
	/* 0x3a */	"getc(b0)",
	/* 0x3b */	"putc(b0)",
	/* 0x3c */	"getchar(b0)",
	/* 0x3d */	"putchar(b0)",
	/* 0x3e */	"gets(b0)",
	/* 0x3f */	"puts(b0)",
	/* 0x40 */	"cd",
	/* 0x41 */	"format",
	/* 0x42 */	"firstfile",
	/* 0x43 */	"nextfile",
	/* 0x44 */	"rename",
	/* 0x45 */	"delete",
	/* 0x46 */	"undelete",
	/* 0x47 */	"AddDevice",
	/* 0x48 */	"RemoteDevice",
	/* 0x49 */	"PrintInstalledDevices",
	/* 0x4a */	"InitCARD",
	/* 0x4b */	"StartCARD",
	/* 0x4c */	"StopCARD",
	/* 0x4d */	"bios_b0_4d",
	/* 0x4e */	"_card_write",
	/* 0x4f */	"_card_read",
	/* 0x50 */	"_new_card",
	/* 0x51 */	"Krom2RawAdd",
	/* 0x52 */	"bios_b0_52",
	/* 0x53 */	"bios_b0_53",
	/* 0x54 */	"_get_errno",
	/* 0x55 */	"_get_error",
	/* 0x56 */	"GetC0Table",
	/* 0x57 */	"GetB0Table",
	/* 0x58 */	"_card_chan",
	/* 0x59 */	"bios_b0_59",
	/* 0x5a */	"bios_b0_5a",
	/* 0x5b */	"ChangeClearPAD",
	/* 0x5c */	"_card_status",
	/* 0x5d */	"_card_wait"
};

char syscalls_c0[][100] =
{
	"EnqueueTimerAndVblankIrqs(priority)",
	"EnqueueSyscallHandler(priority)",
	"SysEnqIntRP(priority, struc)",
	"SysDeqIntRP(priority, struc)",
	"get_free_EvCB_slot()",
	"get_free_TCB_slot()",
	"ExceptionHandler()",
	"InstallExceptionHandlers()",
	"SysInitMemory(addr, size)",
	"SysInitKernelVariables()",
	"ChangeClearRCnt(t, flag)",
	"SystemError",
	"InitDefInt(priority)",
	"SetIrqAutoAck(irq, flag)",
	"return 0",
	"return 0",
	"return 0",
	"return 0",
	"InstallDevices(ttyflag)",
	"FlushStdInOutPut()",
	"return 0",
	"tty_cdevinput(circ, char)",
	"tty_cdevscan()",
	"tty_circgetc(circ)",
	"tty_circputc(char, circ)",
	"oabort(txt1, txt2)",
	"set_card_find_mode(mode)",
	"KernelRedirect(ttyflag)",
	"AdjustA0Table()",
	"get_card_find_mode()"
};